// Code generated by "stringer -type=GridKind"; DO NOT EDIT

package sirpent

import "fmt"

const _GridKind_name = "hex_grid_hexagonal"

var _GridKind_index = [...]uint8{0, 18}

func (i GridKind) String() string {
	if i < 0 || i >= GridKind(len(_GridKind_index)-1) {
		return fmt.Sprintf("GridKind(%d)", i)
	}
	return _GridKind_name[_GridKind_index[i]:_GridKind_index[i+1]]
}
